services:
  - type: web
    name: mlflow-server
    env: python
    plan: starter
    buildCommand: pip install mlflow psycopg2-binary boto3
    startCommand: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@${MLFLOW_DB_HOST}:${MLFLOW_DB_PORT}/${MLFLOW_DB_NAME}
      --default-artifact-root /mnt/data/mlruns
      --host 0.0.0.0
      --port $PORT
    envVars:
      - key: MLFLOW_DB_USER
        value: mlflow_5jwo_user
      - key: MLFLOW_DB_PASSWORD
        value: U8n4JZyJLhTgrv4AWdk482ocsEUz3JpX
      - key: MLFLOW_DB_HOST
        value: dpg-d3cm2aumcj7s73dngiig-a
      - key: MLFLOW_DB_PORT
        value: "5432"
      - key: MLFLOW_DB_NAME
        value: mlflow_5jwo
    disks:
      - name: mlflow-data
        mountPath: /mnt/data
        sizeGB: 10
